// <auto-generated />
using System;
using Manbet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Manbet.Infrastructure.Migrations
{
    [DbContext(typeof(ManbetDBContext))]
    [Migration("20220720234157_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Manbet.Core.Entities.Aposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CasaApostaId")
                        .HasColumnType("int");

                    b.Property<float>("ODD")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("ValorAposta")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CasaApostaId");

                    b.ToTable("Apostas");
                });

            modelBuilder.Entity("Manbet.Core.Entities.CasaAposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CasasAposta");
                });

            modelBuilder.Entity("Manbet.Core.Entities.Saque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destino")
                        .HasColumnType("longtext");

                    b.Property<float>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Saques");
                });

            modelBuilder.Entity("Manbet.Core.Entities.Aposta", b =>
                {
                    b.HasOne("Manbet.Core.Entities.CasaAposta", "CasaAposta")
                        .WithMany()
                        .HasForeignKey("CasaApostaId");

                    b.Navigation("CasaAposta");
                });
#pragma warning restore 612, 618
        }
    }
}
